name: Build MkDocs Artifacts
description: Build MkDocs and Versioning with Mike

inputs:
  docs-version:
    description: "Docs Version"
    required: true

runs:
  using: composite
  steps:
    - name: Configure Git
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Setup gh-pages Branch
      shell: bash
      run: |
        # Store current branch
        CURRENT_BRANCH=$(git branch --show-current)

        # Check if gh-pages branch exists
        if git ls-remote --heads origin gh-pages | grep -q gh-pages; then
          echo "gh-pages branch exists, fetching..."
          git fetch origin gh-pages:gh-pages
        else
          echo "gh-pages branch doesn't exist, creating..."
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initial gh-pages commit"
          git push origin gh-pages
          git checkout "$CURRENT_BRANCH"
        fi

    - name: Build and Deploy Docs with Mike
      shell: bash
      run: |
        echo "Deploying Docs Version: ${{ inputs.docs-version }}"
        uv run mike deploy --push --update-aliases "${{ inputs.docs-version }}" latest

    - name: Set Default Version
      shell: bash
      run: |
        echo "Setting 'Latest' as Default Version"
        uv run mike set-default --push latest
