name: Build MkDocs Artifacts
description: Build MkDocs and versioning with Mike

inputs:
  docs-version:
    description: "Version docs"
    required: true

runs:
  using: composite
  steps:
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
      shell: bash

    - name: Setup gh-pages branch
      run: |
        # Check if gh-pages branch exists remotely
        if git ls-remote --heads origin gh-pages | grep -q gh-pages; then
          echo "gh-pages branch exists, fetching..."
          git fetch origin gh-pages:gh-pages
        else
          echo "gh-pages branch doesn't exist, creating..."
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initial gh-pages commit"
          git push origin gh-pages
          git checkout $CURRENT_BRANCH
        fi
      shell: bash

    - name: Build and deploy docs with Mike
      run: |
        echo "Deploying docs version: ${{ inputs.docs-version }}"
        uv run mike deploy --push --update-aliases ${{ inputs.docs-version }} latest
      shell: bash

    - name: Set default version
      run: |
        echo "Setting latest as default version"
        uv run mike set-default --push latest
      shell: bash
