name: Lint Code

inputs:
  src-project-folder:
    description: "Directory where the project is located"
    required: true
    default: "src"

runs:
  using: composite
  steps:
    - name: Lint with ruff
      id: ruff
      run: |
        echo "Running ruff linter..."  
        uv run ruff check ${{ inputs.src-project-folder }}/
      shell: bash

    - name: Check imports with isort
      run: |
        echo "Running isort..."  
        uv run isort --check ${{ inputs.src-project-folder }}/
      shell: bash

    - name: Cognitive Complexity with complexipy
      run: |
        echo "Running complexipy..."
        uv run complexipy ${{ inputs.src-project-folder }}/
      shell: bash

    - name: Check Mypy
      run: |
        echo "Running Mypy type checker..."
        uv run mypy ${{ inputs.src-project-folder }}/
      shell: bash
