name: Setup Python Environment and uv
description: Setup Python, uv, and dependencies for the project

inputs:
  src-python-version:
    description: "Python version to set up for the project"
    required: true

  dependencies:
    description:
      "Dependency group(s) to install (comma-separated, for use with pyproject.toml)"
    required: true

runs:
  using: composite
  steps:
    - name: Install uv (Python package manager)
      id: setup-uv
      uses: astral-sh/setup-uv@v5

    - name: Install Python via uv
      id: install-python
      shell: bash
      run: |
        echo "Installing Python ${{ inputs.src-python-version }}..."
        uv python install ${{ inputs.src-python-version }}

    - name: Create virtual environment
      id: create-venv
      shell: bash
      run: |
        echo "Creating virtual environment in .venv/ using Python ${{ inputs.src-python-version }}..."
        uv venv .venv --python ${{ inputs.src-python-version }}

    - name: Install dependencies with uv
      id: install-deps
      shell: bash
      run: |
        echo "Activating virtual environment and installing dependencies for group(s): ${{ inputs.dependencies }}"
        source .venv/bin/activate
        uv pip install --group ${{ inputs.dependencies }}

    - name: Verify uv and environment
      id: verify
      shell: bash
      run: |
        source .venv/bin/activate
        echo "uv version:"
        uv --version
        echo "Virtual environments:"
        uv venv list
