name: Setup Python Environment
description: Sets up Python, Poetry, and dependencies for the project

# Define inputs for the action, such as the Python version and the dependencies
# to install
inputs:
  src-python-version:
    description: "Python version to set up for the project"
    required: true
  dependencies:
    description: "Dependencies to install (e.g., test, lint)"
    required: true

runs:
  using: composite
  steps:
    # Step 1: Install the specified version of Python using actions/setup-python
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.src-python-version }}
        cache: "poetry"

    # Step 2: Install Poetry, a tool for managing Python dependencies
    - name: Install Poetry
      uses: snok/install-poetry@v1

    # Step 3: Install dependencies using Poetry
    - name: Install dependencies using Poetry
      run: poetry install --with ${{ inputs.dependencies }}
      shell: bash

    # Step 4: Verify the installation of Poetry and the environment info
    - name: Verify installation
      shell: bash
      run: |
        poetry --version  
        poetry env info
