name: Build MkDocs Artifacts

runs:
  using: composite

  steps:
    - name: Set cache ID based on UTC week number
      id: set-cache-id
      run: |
        echo "Calculating cache ID from UTC week number..."
        echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      shell: bash

    - name: Cache MkDocs dependencies and .cache folder
      id: mkdocs-cache
      uses: actions/cache@v4
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: .cache
        restore-keys: |
          mkdocs-material-

    - name: Build and deploy MkDocs site to gh-deploy branch
      id: deploy-mkdocs
      run: |
        echo "Building and deploying MkDocs site..."
        uv run mkdocs gh-deploy --config-file ./mkdocs.yml --force
      shell: bash
