name: Lint Code

inputs:
  src-project-folder:
    description: "Directory where the project is located"
    required: true
    default: "src"

runs:
  using: composite
  steps:
    - name: Check format with Black
      id: black
      run: |
        echo "Running Black formatter check..."  
        uv run black --check ${{ inputs.src-project-folder }}/
      shell: bash

    - name: Type check with Mypy
      id: mypy
      run: |
        echo "Running Mypy type checker..." 
        uv run mypy ${{ inputs.src-project-folder }}/
      shell: bash

    - name: Lint with Flake8
      id: flake8
      run: |
        echo "Running Flake8 linter..."
        uv run flake8 ${{ inputs.src-project-folder }}/
      shell: bash

    - name: Code quality check with Pylint
      id: pylint
      run: |
        echo "Running Pylint (fail under 8.0)..."
        uv run pylint --fail-under=8 ${{ inputs.src-project-folder }}/
      shell: bash

    - name: Cognitive complexity analysis with Complexipy
      id: complexipy
      run: |
        echo "Running Complexipy for cognitive complexity analysis..."
        uv run complexipy ${{ inputs.src-project-folder }}/
      shell: bash
