name: CI/CD Pipeline

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main, dev]

env:
  SRC_PROJECT_FOLDER: "{{ cookiecutter.project_module_name }}"
  SRC_PROJECT_TESTS: "{{ cookiecutter.project_test_folder_name }}"
  SRC_PYTHON_VERSION: "{{ cookiecutter.project_version_python }}"

jobs:
  setup-lint-test:
    name: Setup, Lint, Test, and Secure Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python & Install Dependencies
        uses: ./.github/actions/setup-python-env
        with:
          src-python-version: ${{'{{'}} env.SRC_PYTHON_VERSION {{'}}'}}
          uv-group: "pipeline"
          uv-extra: "--all-extras"

      - name: Lint Code (ruff, Mypy, Complexipy)
        uses: ./.github/actions/lint-code
        with:
          src-project-folder: ${{'{{'}} env.SRC_PROJECT_FOLDER {{'}}'}}

      - name: Run Tests with Pytest
        uses: ./.github/actions/test-code
        with:
          src-project-folder: ${{'{{'}} env.SRC_PROJECT_FOLDER {{'}}'}}
          src-tests-folder: ${{'{{'}} env.SRC_PROJECT_TESTS {{'}}'}}

      - name: Run Bandit Security Scan
        uses: ./.github/actions/security
        with:
          src-project-folder: ${{'{{'}} env.SRC_PROJECT_FOLDER {{'}}'}}
          src-exclude: ${{'{{'}} env.SRC_PROJECT_TESTS {{'}}'}}

  build-deploy-mkdocs:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Build MkDocs Documentation
    runs-on: ubuntu-latest
    needs: setup-lint-test

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python & Install Dependencies
        uses: ./.github/actions/setup-python-env
        with:
          src-python-version: ${{'{{'}} env.SRC_PYTHON_VERSION {{'}}'}}
          uv-group: "documentation"

      - name: Get Version
        id: version
        uses: ./.github/actions/obtain-version

      - name: Build MkDocs Site with Mike
        uses: ./.github/actions/build-mkdocs
        with:
          docs-version: ${{'{{'}} steps.version.outputs.version {{'}}'}}

  create-release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Create Release
    runs-on: ubuntu-latest
    needs: build-deploy-mkdocs

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python & Install Dependencies
        uses: ./.github/actions/setup-python-env
        with:
          src-python-version: ${{'{{'}} env.SRC_PYTHON_VERSION {{'}}'}}
          uv-group: "pipeline"

      - name: Get Version
        id: version
        uses: ./.github/actions/obtain-version

      - name: Create Release
        id: release
        uses: ./.github/actions/create-release
        with:
          version: ${{'{{'}} steps.version.outputs.version {{'}}'}}
          token: ${{'{{'}} secrets.GITHUB_TOKEN {{'}}'}}

      - name: Release Summary
        run: |
          echo "# Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Version:** ${{'{{'}} steps.release.outputs.version  {{'}}'}}" >> $GITHUB_STEP_SUMMARY
          echo "- **Created:** ${{'{{'}} steps.release.outputs.created  {{'}}'}}" >> $GITHUB_STEP_SUMMARY
