name: Check Security Code
description: Security Scan Python Code with Bandit

inputs:
  src-project-folder:
    description: "Project Directory"
    required: true
    default: "src"

  src-exclude:
    description: "Directory to Exclude from Security Checks"
    required: true
    default: "tests"

runs:
  using: composite
  steps:
    - name: Security Scan with Bandit
      shell: bash
      run: |
        uv run bandit -r "${{ inputs.src-project-folder }}/" --exclude "${{
        inputs.src-exclude }}"
