name: Test Code

inputs:
  src-project-folder:
    description: "Directory where the project is located"
    required: true
    default: "src"

  src-tests-folder:
    description: "Directory where the tests are located"
    required: true
    default: "tests"

runs:
  using: composite
  steps:
    - name: Run tests with Pytest
      id: run-pytest
      shell: bash
      run: |
        echo "Running Pytest on '${{ inputs.src-tests-folder }}'..."
        uv run pytest ${{ inputs.src-tests-folder }}
